version: "3.7"
services:

  postgres:
    image: postgres:10
    volumes:
      - .pgdata:/var/lib/postgresql/data
    env_file: .env
    build:
      context: ./postgres

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  django:
    build: ./src
    command: gunicorn -b :8000 -w 2 conversion_csv.wsgi:application --reload --timeout 3600
    # command: daphne -b 0.0.0.0 -p 9000 conversion_csv.asgi:application
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=conversion_csv.settings.dev
      - PYTHONUNBUFFERED=1

  celery:
    build: ./src
    command: celery worker -A conversion_csv -l info
    depends_on:
      - redis
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=conversion_csv.settings.dev

  nginx:
    image: nginx
    volumes:
      - ./src/conversion_csv/static:/static
      - ./src/conversion_csv/media:/media
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - django
    ports:
      - "80:80"
